// Runs one named test repeatedly while busy-loop processes saturate the CPUs,
// recording each run's exit status, duration and output as JSON lines. Used to
// check whether a timing-sensitive test depends on host speed.
// Run it on a dedicated test host, never a workstation: the workers
// deliberately saturate every CPU.
// Usage: bun scripts/load-probe.mjs FILE TEST_NAME [RUNS] [--workers COUNT]
// TEST_BUN selects the Bun that runs the test. No load is generated by default.
import { spawn } from 'node:child_process'
import { performance } from 'node:perf_hooks'

const [file, name, ...args] = process.argv.slice(2)
const runsArg = args[0] && !args[0].startsWith('--') ? args.shift() : '20'
let workersArg = '0'
if (args.length === 2 && args[0] === '--workers') workersArg = args.splice(0)[1]
if (!file || !name || args.length)
  throw new Error('usage: load-probe.mjs FILE TEST_NAME [RUNS] [--workers COUNT]')
const runs = Number(runsArg)
const count = Number(workersArg)
if (!Number.isInteger(runs) || runs < 1 || !Number.isInteger(count) || count < 0)
  throw new Error(
    'RUNS must be a positive integer and WORKERS a non-negative integer',
  )

let group
let activeTest
const stop = () => {
  if (group?.pid) {
    try {
      process.kill(-group.pid, 'SIGKILL')
    } catch (error) {
      if (error.code !== 'ESRCH') throw error
    }
  }
  activeTest?.kill('SIGKILL')
}
process.once('exit', stop)
if (count > 0) {
  console.error(`WARNING: generating CPU load with ${count} workers; use a dedicated test host.`)
  // One detached leader owns all workers in the same process group. The IPC
  // lifeline also kills the group if this parent disappears without an exit hook.
  group = spawn(process.execPath, ['-e', `
    const { spawn } = require('node:child_process');
    process.on('disconnect', () => process.kill(-process.pid, 'SIGKILL'));
    for (let i = 0; i < ${count}; i++) {
      spawn(process.execPath, ['-e', 'for (;;) { Math.sqrt(Math.random()) }'], { stdio: 'ignore' });
    }
  `], { detached: true, stdio: ['ignore', 'ignore', 'ignore', 'ipc'] })
  group.on('error', (error) => { throw error })
}
process.on('SIGINT', () => {
  stop()
  process.exit(130)
})
process.on('SIGTERM', () => {
  stop()
  process.exit(143)
})

console.log(
  JSON.stringify({
    runtime: process.version,
    executable: process.execPath,
    file,
    name,
    runs,
    workers: count,
    loadGroupPid: group?.pid ?? null,
  }),
)
let failures = 0
try {
  for (let run = 1; run <= runs; run++) {
    const start = performance.now()
    const child = spawn(
      process.env.TEST_BUN ?? process.execPath,
      ['test', file, '--test-name-pattern', name],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    )
    activeTest = child
    let output = ''
    for (const stream of [child.stdout, child.stderr])
      stream.on('data', (chunk) => {
        output += chunk
      })
    const code = await new Promise((resolve, reject) => {
      child.on('error', reject)
      child.on('close', resolve)
    })
    activeTest = undefined
    if (code !== 0) failures++
    console.log(
      JSON.stringify({
        run,
        code,
        durationMs: Math.round(performance.now() - start),
        output,
      }),
    )
  }
} finally {
  stop()
}
console.log(JSON.stringify({ passes: runs - failures, failures, runs, workers: count }))
process.exitCode = failures ? 1 : 0
